/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MarkdownEditor: typeof import('./src/components/markdown/MarkdownEditor.vue')['default']
    MarkdownViewer: typeof import('./src/components/markdown/MarkdownViewer.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    MyArticleEdit: typeof import('./src/components/MyArticleEdit.vue')['default']
    MyArticlesList: typeof import('./src/components/MyArticlesList.vue')['default']
    MyCategoryList: typeof import('./src/components/MyCategoryList.vue')['default']
    MyDashboardCard: typeof import('./src/components/MyDashboardCard.vue')['default']
    MyRecentArticlesCard: typeof import('./src/components/MyRecentArticlesCard.vue')['default']
    MySideBar: typeof import('./src/layout/components/MySideBar.vue')['default']
    MyTagList: typeof import('./src/components/MyTagList.vue')['default']
    MyTopBar: typeof import('./src/layout/components/MyTopBar.vue')['default']
    MyUserList: typeof import('./src/components/MyUserList.vue')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
  }
}
