/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MarkdownEditor: typeof import('./src/components/markdown/MarkdownEditor.vue')['default']
    MarkdownViewer: typeof import('./src/components/markdown/MarkdownViewer.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    MyArticlesList: typeof import('./src/components/MyArticlesList.vue')['default']
    MyDashboardCard: typeof import('./src/components/MyDashboardCard.vue')['default']
    MyRecentArticlesCard: typeof import('./src/components/MyRecentArticlesCard.vue')['default']
    MySideBar: typeof import('./src/components/MySideBar.vue')['default']
    MyTopBar: typeof import('./src/components/MyTopBar.vue')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
